#!/usr/bin/env bash
#script to output Best school 10 times using while loop with a Hi on the 9th line
COUNT=0
while((COUNT<10));do
	if [ "$COUNT" -eq 7 ] ;then
		echo "good luck"
	elif [ "$COUNT" -eq 3 ] ;then
		echo "bad luck"
	else 
		echo "Best School"
	fi
((COUNT++))
done;
