#!/usr/bin/env bash
#list all files in each line without the hyphen
FILES="$(ls)"
for i in $FILES;
do
	NEW=$(find . -maxdepth 2 -name "$i" | cut -d "-" -f2)
	#OLD=$(find . -maxdepth 1 -name "$NEW" | cut -d "/" -f2)
	echo "$NEW"
done
