#!/usr/bin/env bash
#starts stop restart script depending on the argument passed
if [ $# -eq 1 ] 
then
	OPTION="$1"
	case $OPTION in
	start)
	./manage_my_process start
	pgrep -f './manage_my_process' > /var/run/my_process.pid && echo "manage_my_process started"
	;;
	stop)
	./manage_my_process stop
	rm /var/run/my_process.pid && echo "manage_my_process stopped"
	;;
	restart)
	./manage_my_process stop
	rm /var/run/my_process.pid && ./manage_my_process start
	pgrep -f './manage_my_process' > /var/run/my_process.pid && echo "manage_my_process restarted"
	;;
	*)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
       esac
else 
	echo "Usage: manage_my_process {start|stop|restart}"
fi
